# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. 
# A copy of the License is located at
#    http://aws.amazon.com/apache2.0/
# or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. See the License for the specific language governing permissions and limitations under the License.

AWSTemplateFormatVersion: 2010-09-09

Description: Stack to deploy a highly available, elastic, scalable Project REDCap environment. This master stack launches multiple nested stacks for different tiers.



Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General AWS
      Parameters:
        - EC2KeyName
        - AccessCidr
    - Label:
          default: DNS and SSL
      Parameters:
        - EBEndpoint
        - UseRoute53Boolean
        - UseACMBoolean
        - HostedZoneId
        - HostedZoneName
        - DomainName
    - Label:
          default: E-Mail
      Parameters:
        - SESUsername
        - SESPassword
    - Label:
        default: Database Tier
      Parameters:
        - MultiAZDatabase
        - DatabaseInstanceType
        - DatabaseMasterPassword
    - Label:
        default: Web Tier
      Parameters:
        - WebInstanceType
        - WebAsgMax
        - WebAsgMin
    - Label:
        default: Project REDCap Source Code
      Parameters:
        - RedcapS3Bucket
        - RedcapS3Key
    
    
    ParameterLabels:
      EC2KeyName:
        default: EC2 Key Pair
      AccessCidr:
        default: Project REDCap Access From

      UseRoute53Boolean:
        default: Use Route 53?
      UseACMBoolean:
        default: Use AWS Certificate Manager?
      HostedZoneId:
        default: Route53 Hosted Zone ID
      HostedZoneName:
        default: Hosted Zone
      DomainName:
        default: Site Domain

      SESUsername:
        default: SES Username
      SESPassword:
        default: SES Password

      MultiAZDatabase:
        default: Use Primary and Standby Database Instances?
      DatabaseInstanceType:
        default: DB Instance Class
      DatabaseMasterPassword:
        default: DB Master Password


      WebAsgMax:
        default: Web ASG Max
      WebAsgMin:
        default: Web ASG Min
      WebInstanceType:
        default: Web Tier Instance Type




Parameters:
  EC2KeyName:
    ConstraintDescription: Must be letters (upper or lower), numbers, and special characters.
    Description: Name of an EC2 KeyPair. Your bastion & Web instances will launch with this KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
  AccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: The CIDR IP range that is permitted to access your Project REDCap site. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
    Default: 0.0.0.0/0


  EBEndpoint:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: '[ REQUIRED ] The unique name to use for your Elastic Beanstalk URL (will be rendered http://(EBEndpoint).(region).elasticbeanstalk.com)'
    Type: String
    Default: myredcap
  UseRoute53Boolean:
    AllowedValues:
      - true
      - false
    Default: true
    Description: Specifies whether a record set should be created in Route 53 for your REDCap domain name.  If not, you will recieve a default Elastic Beanstalk DNS name (e.g. redcap.us-east-1.elasticbeanstalk.com).
    Type: String
  UseACMBoolean:
    AllowedValues:
      - true
      - false
    Default: true
    Description: '[ Requires Route53 ] Specifies whether an SSL certificate should be generated for your domain name using AWS Certificate Manager (ACM).  If one is not generated, HTTP will be used and an SSL certificate can be applied after deployment.'
    Type: String
  HostedZoneId:
    Description: '[ Optional, only if using Route53 ] The Route 53 hosted zone ID to create the domain in (e.g. example.edu).'
    #Type: AWS::Route53::HostedZone::Id
    Type: String
  HostedZoneName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: '[ Optional, only if using Route53 ] The Route 53 hosted zone to create the domain in (e.g. example.edu).'
    Type: String
  DomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: '[ Optional, only if using Route53 ] The sub-domain name of the Project REDCap site.  This sub-domain will be prepended your specified Hosted Zone (e.g. redcap in redcap.example.edu).'
    Type: String



  SESUsername:
    Type: String
    Description: Username to use for authentication to SES.
  SESPassword:
    Type: String
    Description: Username to use for authentication to SES.
    NoEcho: true


  MultiAZDatabase:
    AllowedValues:
      - true
      - false
    Default: false
    Description: Specifies whether a to deploy the AWS Aurora MySQL Database in Multi-AZ configuration.
    Type: String
  DatabaseInstanceType:
    AllowedValues:
      - db.t2.small
      - db.t2.medium
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    ConstraintDescription: Must be a valid RDS instance class.
    Default: db.t2.small
    Description: The Amazon RDS database instance class.
    Type: String
  DatabaseMasterPassword:
    AllowedPattern: ^([a-zA-Z0-9`~!#$%^&*()_+,\\-])*$
    ConstraintDescription: Must be letters (upper or lower), numbers, spaces, and these special characters `~!#$%^&*()_+,-
    Description: The Amazon RDS master password. Letters, numbers, spaces, and these special characters `~!#$%^&*()_+,-
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String


  WebInstanceType:
    AllowedValues:
      - t2.nano 
      - t2.micro 
      - t2.small 
      - t2.medium 
      - t2.large 
      - t2.xlarge 
      - t2.2xlarge 
      - m3.medium 
      - m3.large 
      - m3.xlarge 
      - m3.2xlarge 
      - m4.large 
      - m4.xlarge 
      - m4.2xlarge 
      - m4.4xlarge 
      - m4.10xlarge 
      - m4.16xlarge 
      - m5.large 
      - m5.xlarge 
      - m5.2xlarge 
      - m5.4xlarge 
      - m5.12xlarge 
      - m5.24xlarge 
      - c3.large 
      - c3.xlarge 
      - c3.2xlarge 
      - c3.4xlarge 
      - c3.8xlarge 
      - c4.large 
      - c4.xlarge 
      - c4.2xlarge 
      - c4.4xlarge 
      - c4.8xlarge 
      - c5.large 
      - c5.xlarge 
      - c5.2xlarge 
      - c5.4xlarge 
      - c5.9xlarge 
      - c5.18xlarge
      - r3.large 
      - r3.xlarge 
      - r3.2xlarge 
      - r3.4xlarge 
      - r3.8xlarge 
      - r4.large 
      - r4.xlarge 
      - r4.2xlarge 
      - r4.4xlarge 
      - r4.8xlarge 
      - r4.16xlarge 
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: t2.micro
    Description: The Amazon EC2 instance type for your web instances.
    Type: String
  WebAsgMax:
    AllowedPattern: ^((?!0$)[1-2]?[0-9]|30)$
    ConstraintDescription: Must be a number between 1 and 30.
    Default: 1
    Description: Specifies the maximum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  WebAsgMin:
    AllowedPattern: ^([0-0]?[0-9]|10)$
    ConstraintDescription: Must be a number between 0 and 10.
    Default: 1
    Description: Specifies the minimum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  RedcapS3Bucket:
    Description: "S3 bucket that contains your REDCap binary file"
    Type: String
    Default: redcap-test
  RedcapS3Key:
    Description: "S3 Key that points to your Redcap Binary file"
    Type: String
    Default: redcap8.4.3.zip

  
Conditions:
  DeployRoute53: 
    !Equals [ true, !Ref UseRoute53Boolean ]
  DeployACM: !And 
    - !Equals [ true, !Ref UseACMBoolean ]
    - !Condition DeployRoute53


Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/project-redcap-aws-automation/01-rc-vpc.yaml
      Parameters:
        AccessCidr: !Ref 'AccessCidr'
        RedcapS3Bucket: !Ref 'RedcapS3Bucket'
        UseACMBoolean: !Ref 'UseACMBoolean'
        S3FileRepositoryBucket: !Sub '${AWS::AccountId}-${AWS::StackName}-redcaprepository'
        EBBucket: !Sub '${AWS::AccountId}-${AWS::StackName}-redcapebapp'
  certificate:
    Condition: DeployACM
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        R53HostedZoneId: !Ref 'HostedZoneId'
        R53DomainName: !Join ['', [!Ref DomainName, '.', !Ref HostedZoneName]]
      TemplateURL: https://s3.amazonaws.com/project-redcap-aws-automation/01-rc-certificate.yaml
  redcapelasticbeanstalk:
    DependsOn: [ VPCStack ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EBBucket: 
          !Sub '${AWS::AccountId}-${AWS::StackName}-redcapebapp'
        SESUsername:
          !Ref SESUsername
        SESPassword:
          !Ref SESPassword
        DatabaseMasterPassword:
          !Ref DatabaseMasterPassword
        DatabaseInstanceType:
          !Ref DatabaseInstanceType
        MultiAZDatabase:
          !Ref MultiAZDatabase
        SslCertificate:
          !If [ DeployACM, !GetAtt [ certificate, Outputs.CertificateArn ], '' ]
        WebAsgMax:
          !Ref WebAsgMax
        WebAsgMin:
          !Ref WebAsgMin
        WebInstanceType:
          !Ref WebInstanceType
        S3AccessKey:
          !GetAtt 'VPCStack.Outputs.S3AccessKey'
        S3SecretKey:
          !GetAtt 'VPCStack.Outputs.S3SecretKey'
        S3FileRepositoryBucket: 
          !Sub '${AWS::AccountId}-${AWS::StackName}-redcaprepository'
        EBEndpoint:
          !Ref EBEndpoint
        UseRoute53Boolean:
          !Ref UseRoute53Boolean
        UseACMBoolean:
          !Ref UseACMBoolean
        HostedZoneName:
          !If [ DeployRoute53, !Ref HostedZoneName, '' ]
        DomainName:
          !If [ DeployRoute53, !Ref DomainName, '' ]
        RedcapS3Bucket:
          !Ref RedcapS3Bucket
        RedcapS3Key:
          !Ref RedcapS3Key
        EC2KeyName:
          !Ref EC2KeyName
        VPCId:
          !GetAtt 'VPCStack.Outputs.VPCId'
        SubnetPublicA:
          !GetAtt 'VPCStack.Outputs.SubnetPublicA'
        SubnetPublicB:
          !GetAtt 'VPCStack.Outputs.SubnetPublicB'
        SubnetAppA:
          !GetAtt 'VPCStack.Outputs.SubnetAppA'
        SubnetAppB:
          !GetAtt 'VPCStack.Outputs.SubnetAppB'
        SubnetDataA:
          !GetAtt 'VPCStack.Outputs.SubnetDataA'
        SubnetDataB:
          !GetAtt 'VPCStack.Outputs.SubnetDataB'
        SGPublic:
          !GetAtt 'VPCStack.Outputs.SGPublic'
        SGApp:
          !GetAtt 'VPCStack.Outputs.SGApp'
        SGData:
          !GetAtt 'VPCStack.Outputs.SGData'
        EBServiceRole:
          !GetAtt 'VPCStack.Outputs.EBServiceRole'      
        EBInstanceProfile:
          !GetAtt 'VPCStack.Outputs.EBInstanceProfile'
        TempEC2InstanceProfile:
          !GetAtt 'VPCStack.Outputs.TempEC2InstanceProfile'
      TemplateURL: https://s3.amazonaws.com/project-redcap-aws-automation/02-rc-elasticbeanstalk.yaml
  route53:
    Condition: DeployRoute53
    DependsOn: redcapelasticbeanstalk
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DnsEndpoint:
          !GetAtt redcapelasticbeanstalk.Outputs.PublicAlbDnsName
        HostedZoneName:
          !Ref HostedZoneName
        DomainName:
          !Ref DomainName
      TemplateURL: https://s3.amazonaws.com/project-redcap-aws-automation/03-rc-route53.yaml

Outputs:
  REDCApURL:
    Value: !If [DeployRoute53, !If [DeployACM, !Join ['', ['https://', !Ref DomainName, '.', !Ref HostedZoneName, '/']], !Join ['', ['http://', !Ref DomainName, '.', !Ref HostedZoneName, '/']]], !Join ['', ['http://', !Ref EBEndpoint, '.', !Ref 'AWS::Region', '.elasticbeanstalk.com']]]